module.exports = global.config = {
  baseURL: 'https://api.iprove.ng/',
  appURL: 'https://iprove.ng',
  // baseURL: 'http://localhost:8082/',
  // appURL: 'http://localhost:3005/',
  publicKey: 'FLWPUBK-ae46134bb4febc6e69c9fc4adae49983-X',
  verification: {
    check: {
      price: 10,
      page: '/nin/check',
      title: 'Check Identity',
      status: 'closed',
      selected: false,
    },
    identity: {
      price: 20,
      page: '/nin/verification',
      title: 'Verify Identity',
      status: 'closed',
      selected: false,
    },
    certificate: {
      price: 30,
      page: '/certificate/verification',
      title: 'Verify Certificate',
      status: 'closed',
      selected: false,
    },
    address: {
      price: 40,
      page: '/address/verification',
      title: 'Verify Address',
      status: 'closed',
      selected: false,
    },
    business: {
      price: 50,
      page: '/business/verification',
      title: 'Verify Business',
      status: 'closed',
      selected: false,
    },
    guarantor: {
      price: 100,
      page: '/guarantor/verification',
      title: 'Verify Guarantor',
      status: 'closed',
      selected: false,
    },
    property: {
      price: 150,
      page: '/property/verification',
      title: 'Verify Property',
      status: 'closed',
      selected: false,
    },
    employment: {
      price: 200,
      page: '/employment/verification',
      title: 'Verify Employment',
      status: 'closed',
      selected: false,
    },
  },
}
